name: Publish release on tag push

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_FILE_NAME: 'css-pokemon-gameboy-${{ github.ref_name }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build the minified css to dist-release
        run: bun run build:css

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ../${{ env.RELEASE_FILE_NAME }}.min.zip
          path: 'template.html styles'
          directory: 'dist-release'

      - name: Build the full css to dist-release
        run: bun run build:css:full

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ../${{ env.RELEASE_FILE_NAME }}.zip
          path: 'template.html styles'
          directory: 'dist-release'

      - name: Create Release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.RELEASE_FILE_NAME }}.min.zip,${{ env.RELEASE_FILE_NAME }}.zip'
          removeArtifacts: true
          body: 'Automatic release created by GitHub Action.'
          prerelease: true
